# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FsMuQVnMaUajnJHTkV8AVGEqC9wnXVo3
"""

from setuptools import setup

setup(
    name='underwater_vision',        # Name of your library
    version='1.0',                   # Version number
    description='A library for underwater images augmentation',
    author='ayan-shahab766',              # Put your name here
    py_modules=['underwater_vision'], # The name of your .py file (without .py)
    install_requires=[               # Dependencies it will auto-install
        'numpy',
        'opencv-python'
    ],
)